name: mqtt
services:
  mqtt-net-service:
    build: .                  # se va a DockerFile y vuele
    image: net-serv           # vuelve aqui para arrancar la imagen creada con la configuarcion de DockerFile
    restart: unless-stopped
    environment:
      DOTNET_ENVIRONMENT: Production

# docker compose up -d --build
  # build construye una imagen, up crea/actualiza el contenedor del servicio y lo arranca
  # d lo deja funcionando en segundo plano

# docker compose ps 
# docker compose logs --tail 50 -f mqtt